### ISSUE TITLE
Move the certificate storage to the Library directory

### ISSUE THREAD

**Issue by joeljfischer** [smartdevicelink/sdl_security_ios#15]
https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW1

See this link. It should either be put into the caches sub-directory (so that it won't be saved to iCloud, but it may get cleared if device storage is very low. Or it should be in the Application Support directory, which will be backed up to iCloud but won't be cleared if device storage is low.

**Comment by NicoleYarroch** [comment]
Fixed in PR #22
