### ISSUE TITLE
Error codes returned by the security manager should be more human readable

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_security_ios#16]
If the security manager setup fails for any reason we pass back a rather unhelpful error:
`Error Domain=com.sdl.security Code=7 "(null)"`. The error code should be made human readable so developers know what went wrong even if they do not have access to the error codes.

**Comment by joeljfischer** [comment]
This is probably because the known keys in the `userInfo` dictionary aren't filled?

**Comment by NicoleYarroch** [comment]
Fixed in PR #18
