### ISSUE TITLE
Encrypt and decrypt certificate data saved to disk

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_security_ios#26]
We should encrypt data being saved to disk and decrypt certificate data being retrieved.

**Comment by joeljfischer** [comment]
I've looked into this in the past and unfortunately it appears that the data can't be encrypted / decrypted on demand automatically. It would be decrypted when the user unlocks the device, which makes it impossible to work correctly if the device is locked. We could perhaps do it manually, but then we have to store a key to unlock it in the app, which kind of defeats the purpose.
