### ISSUE TITLE
Static library does not compile on Xcode 12

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_security_ios#56]
### Bug Report
The OpenSSL library included in the library for developer convenience does not compile on Xcode 12 due to the OpenSSL library files _libcrypto.a_ and _libssl.a_ not being built for the i368 architectures. 

##### Reproduction Steps
1. Try to build the static target on Xcode 12

##### Expected Behavior
The build succeeds

##### Observed Behavior
The build fails due to issues with the OpenSSL library

##### OS & Version Information
* SDL Security iOS Version: 1.0
* SDL iOS Version: n/a
* iOS Version: n/a
* Testing Against: n/a

**Comment by joeljfischer** [comment]
Also should investigate static pod / SPM builds?
