### ISSUE TITLE
Podspec file should be removed

### ISSUE THREAD

**Issue by NicoleYarroch** [smartdevicelink/sdl_security_ios#9]
A `.podspec` file was added to the library so it can be installed as a dependency via CocoaPods. However it seems to have no purpose since the installed files can not be utilized. It should be removed or, if it does have a purpose, more information on how to use it should be added to the README.

**Comment by joeljfischer** [comment]
It should probably just be updated. It's possible to install a pod statically as well.

**Comment by NicoleYarroch** [comment]
Fixed in PR #20
